name: CI
concurrency:
  group: rails-${{ github.head_ref || 'main' }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ruby_lints:
    name: Ruby Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Standardrb
        run: bundle exec standardrb
      - name: Run bundle-audit
        run: bundle exec bundle audit --update
